---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment 
  labels:
    app: server 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server 
  template:
    metadata:
      labels:
        app: server #nginx-1
    spec:
      containers:
      - name: env-tomcat #nginx-2
        image: eu.gcr.io/devops-p/docker
      - name: server #nginx-1
        image: eu.gcr.io/juice-shop-project/nginx:v1
        ports:
        - containerPort: 80