---
apiVersion: v1
kind: Pod
metadata:
  name: srv-tomcat
  labels:
    app: srv-tomcat #tier: srv_tomcat
spec:
  containers:
  - name: env-tomcat
    image: eu.gcr.io/devops-p/docker
  - name: server
    image: eu.gcr.io/juice-shop-project/nginx:v1
    ports:
    - containerPort: 80
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
  #restartPolicy: Never  
    resources:      
      limits:
        cpu: "1"
        memory: "1000Mi"
      requests:
        cpu: 800m
        memory: "500Mi"
    volumeMounts:
    - name: nginx-proxy-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  volumes:
  - name: nginx-proxy-config
    configMap:
      name: srv-tomcat-nginx-conf
      