apiVersion: v1
kind: Service
metadata:
  name: appli-ku #LBforKC 
  labels:
    server: nginx
spec:
  selector:
    app: appli-ku
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9377
  type: LoadBalancer
  loadBalancerIP: ""
  
